# FOR DEVELOPMENT ONLY.

version: '3'

services:
  postgres:
    container_name: postgres-QuikDev
    image: postgres:16.0
    env_file:
      - .env
    volumes:
      - pg-volume:/var/lib/postgresql/data
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
  
  mailhog:
      container_name: mailhog-QuikDev
      image: mailhog/mailhog:v1.0.1
      ports:
        - '1025:1025' # SMTP.
        - '8025:8025' # Interface Web.

volumes:
  pg-volume:
